name: video_frontend_final
description: A video downloader application with support for multiple platforms.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  dio: ^5.4.3+1
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  url_launcher: ^6.1.11
  share_plus: ^11.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.3.8
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.2.3
  video_player: ^2.8.2
  chewie: ^1.7.0
  fluttertoast: ^8.2.4
  percent_indicator: ^4.2.3
  path: ^1.8.3
  shimmer: ^3.0.0
  video_thumbnail: ^0.5.6
  open_filex: ^4.7.0
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/downloader_logo.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: false
  image_path: "assets/downloader_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/downloader_logo.png"
